In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt


In [2]:
df=pd.read_csv('data_core.csv')

In [4]:
df.head()

Temparature  Humidity  Moisture Soil Type  Crop Type  Nitrogen  Potassium  \
0         26.0      52.0      38.0     Sandy      Maize        37          0   
1         29.0      52.0      45.0     Loamy  Sugarcane        12          0   
2         34.0      65.0      62.0     Black     Cotton         7          9   
3         32.0      62.0      34.0       Red    Tobacco        22          0   
4         28.0      54.0      46.0    Clayey      Paddy        35          0   

   Phosphorous Fertilizer Name  
0            0            Urea  
1           36             DAP  
2           30        14-35-14  
3           20           28-28  
4            0            Urea

In [5]:
df.isnull().sum()

Temparature        0
Humidity           0
Moisture           0
Soil Type          0
Crop Type          0
Nitrogen           0
Potassium          0
Phosphorous        0
Fertilizer Name    0
dtype: int64

In [ ]:
df_cleaned = df.dropna()
print(df_cleaned.isnull().sum())

In [ ]:
for col in df.columns:
    if(df[col].dtype == 'object'):
        df[col] = df[col].fillna(df[col].mode()[0])
    else:
        df[col] = df[col].fillna(df[col].mean())

In [23]:
import pandas as pd
from sklearn.preprocessing import LabelEncoder

df = pd.read_csv('data_core.csv')

columns = ['Temparature', 'Humidity', 'Moisture', 'Soil Type', 'Crop Type']
df_selected = df[columns]

le_soil = LabelEncoder()
le_crop = LabelEncoder()

df_selected['Soil Type'] = le_soil.fit_transform(df_selected['Soil Type'])
df_selected['Crop Type'] = le_crop.fit_transform(df_selected['Crop Type'])

print(df_selected.head())


   Temparature  Humidity  Moisture  Soil Type  Crop Type
0         26.0      52.0      38.0          4          3
1         29.0      52.0      45.0          2          8
2         34.0      65.0      62.0          0          1
3         32.0      62.0      34.0          3          9
4         28.0      54.0      46.0          1          6


C:\Users\Dell\AppData\Local\Temp\ipykernel_23608\781752557.py:12: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_selected['Soil Type'] = le_soil.fit_transform(df_selected['Soil Type'])
C:\Users\Dell\AppData\Local\Temp\ipykernel_23608\781752557.py:13: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_selected['Crop Type'] = le_crop.fit_transform(df_selected['Crop Type'])


In [25]:
from sklearn.model_selection import train_test_split

X = df_selected[['Temparature', 'Humidity', 'Moisture', 'Soil Type']]
y = df_selected['Crop Type']

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

In [26]:
from sklearn.ensemble import RandomForestClassifier

model = RandomForestClassifier()
model.fit(X_train, y_train)


RandomForestClassifier()

In [27]:
from sklearn.model_selection import train_test_split

X = df_selected[['Temparature', 'Humidity', 'Moisture', 'Soil Type']]
y = df_selected['Crop Type']

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)


In [28]:
# Model accuracy
score = model.score(X_test, y_test)
print("Test accuracy:", score)

# Detailed evaluation (optional)
from sklearn.metrics import classification_report, confusion_matrix
y_pred = model.predict(X_test)
print(confusion_matrix(y_test, y_pred))
print(classification_report(y_test, y_pred))


Test accuracy: 0.090625
[[14 14 16 23  6 11 11 14 18  5 12]
 [10 14 15 17  9 12 16 13 11 16  8]
 [17 22  9 14 15  8 11 13  8 16 12]
 [16  9  9 18 10 13 14 12 16 16 14]
 [21 24 11 13 13 12  7 17 12 11  8]
 [13 18 14 11 14 15 14 15 13 10 17]
 [12 13 16  7 16 17 14 14 12  9 16]
 [14  4 16  8 14  7 10 15 11 14 12]
 [20 18 18 18 13 14 16  7 15 25 10]
 [ 9 11 12 16 16 10 11  9 11 10 15]
 [16 14 20 12 18 12 18 13  8  6  8]]
              precision    recall  f1-score   support

           0       0.09      0.10      0.09       144
           1       0.09      0.10      0.09       141
           2       0.06      0.06      0.06       145
           3       0.11      0.12      0.12       147
           4       0.09      0.09      0.09       149
           5       0.11      0.10      0.11       154
           6       0.10      0.10      0.10       146
           7       0.11      0.12      0.11       125
           8       0.11      0.09      0.10       174
           9       0.07      0.08     

In [ ]:
# Example: Predict crop type for new soil/values


sample = [[25.5, 60.0, 40.0, 2]]
prediction = model.predict(sample)
print("Predicted Crop Type (encoded):", prediction)


Predicted Crop Type (encoded): [0]


c:\Users\Dell\anaconda3\Lib\site-packages\sklearn\utils\validation.py:2739: UserWarning: X does not have valid feature names, but RandomForestClassifier was fitted with feature names
  warnings.warn(


In [ ]:
# Example test case:

soil_type_encoded = le_soil.transform(['Loamy'])[0]  # Replace 'Loamy' with any soil type

test_sample = [[25.0, 60.0, 35.0, soil_type_encoded]]
pred_crop_encoded = model.predict(test_sample)
pred_crop = le_crop.inverse_transform(pred_crop_encoded)
print("Predicted crop type:", pred_crop[0])


Predicted crop type: Paddy


c:\Users\Dell\anaconda3\Lib\site-packages\sklearn\utils\validation.py:2739: UserWarning: X does not have valid feature names, but RandomForestClassifier was fitted with feature names
  warnings.warn(


In [31]:
from sklearn.model_selection import cross_val_score
scores = cross_val_score(model, X, y, cv=5)
print("Cross-validation scores:", scores)
print("Mean:", scores.mean())


Cross-validation scores: [0.09     0.085625 0.0825   0.095625 0.105   ]
Mean: 0.09175


In [ ]:
threshold = 30 
df_selected['Water Available'] = df_selected['Moisture'] > threshold

print(df_selected[['Moisture', 'Water Available']].head())


   Moisture  Water Available
0      38.0             True
1      45.0             True
2      62.0             True
3      34.0             True
4      46.0             True


C:\Users\Dell\AppData\Local\Temp\ipykernel_23608\2394076899.py:4: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_selected['Water Available'] = df_selected['Moisture'] > threshold


In [39]:
moisture_values = [12.00, 25.22, 29.99, 30.01, 38.34, 43.80, 58.28, 18.40, 31.50, 60.00, 45.67, 28.25, 50.00, 22.99, 37.15, 65.43]
soil_types = ['Sandy', 'Loamy', 'Clayey', 'Black', 'Red']

# Sample mapping for crop recommendation (customize as needed)
def recommend_crop(moisture, soil_type):
    if soil_type == 'Sandy':
        if moisture < 30: return 'Barley'
        elif moisture < 45: return 'Millets'
        else: return 'Maize'
    elif soil_type == 'Loamy':
        if moisture < 30: return 'Cotton'
        elif moisture < 45: return 'Wheat'
        else: return 'Sugarcane'
    elif soil_type == 'Clayey':
        if moisture < 30: return 'Pulses'
        elif moisture < 45: return 'Paddy'
        else: return 'Ground Nuts'
    elif soil_type == 'Black':
        if moisture < 30: return 'Oil seeds'
        elif moisture < 45: return 'Millets'
        else: return 'Cotton'
    elif soil_type == 'Red':
        if moisture < 30: return 'Tobacco'
        elif moisture < 45: return 'Ground Nuts'
        else: return 'Sugarcane'
    else:
        return 'Unknown'

def moisture_status(moisture):
    if moisture < 25:
        return "Bad"
    elif 25 <= moisture < 45:
        return "Average"
    else:
        return "Good"

def recommend_fertilizer(moisture):
    if moisture < 30:
        return "Urea, DAP, 17-17-17, 20-20"
    elif moisture < 45:
        return "DAP, 28-28, Urea, 10-26-26"
    else:
        return "14-35-14, 28-28, 17-17-17, Urea"

print(f"{'Moisture':>9} | {'Soil':<7} | {'Status':>8} | {'Crop':<12} | {'Recommended Fertilizers':<30}")
print("-" * 80)


for i, moisture in enumerate(moisture_values):
    soil_type = soil_types[i % len(soil_types)]
    status = moisture_status(moisture)
    crop = recommend_crop(moisture, soil_type)
    fertilizers = recommend_fertilizer(moisture)
    print(f"{moisture:9.2f} | {soil_type:<7} | {status:8} | {crop:<12} | {fertilizers:<30}")


 Moisture | Soil    |   Status | Crop         | Recommended Fertilizers       
--------------------------------------------------------------------------------
    12.00 | Sandy   | Bad      | Barley       | Urea, DAP, 17-17-17, 20-20    
    25.22 | Loamy   | Average  | Cotton       | Urea, DAP, 17-17-17, 20-20    
    29.99 | Clayey  | Average  | Pulses       | Urea, DAP, 17-17-17, 20-20    
    30.01 | Black   | Average  | Millets      | DAP, 28-28, Urea, 10-26-26    
    38.34 | Red     | Average  | Ground Nuts  | DAP, 28-28, Urea, 10-26-26    
    43.80 | Sandy   | Average  | Millets      | DAP, 28-28, Urea, 10-26-26    
    58.28 | Loamy   | Good     | Sugarcane    | 14-35-14, 28-28, 17-17-17, Urea
    18.40 | Clayey  | Bad      | Pulses       | Urea, DAP, 17-17-17, 20-20    
    31.50 | Black   | Average  | Millets      | DAP, 28-28, Urea, 10-26-26    
    60.00 | Red     | Good     | Sugarcane    | 14-35-14, 28-28, 17-17-17, Urea
    45.67 | Sandy   | Good     | Maize        | 